<?php

namespace RubahApi\KelurahanBundle\Repository;

/**
 * KelurahanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KelurahanRepository extends \Doctrine\ORM\EntityRepository
{
}
